### PR TITLE
add_scheduled_task and required SQL removal

### PR DESCRIPTION
**Pull request by amarendra-dianomic**

### CODE REVIEW

**Comment by praveen-garg** [comment]
it should not be needed at all. We need to fix debian post inst script too to replace `add_enabled_schedule` with add_scheduled_task

**Review by praveen-garg — CHANGES_REQUESTED** [review]
requires postinstl script fixes

**Comment by amarendra-dianomic** [comment]
@praveen-garg changes done. Pl check.

**Comment by amarendra-dianomic** [comment]
@praveen-garg changes done. Pl check.

**Review by praveen-garg — APPROVED** [review]

**Review by ajabble — APPROVED** [review]

**Pull request merged**
